version: '3'

services:
  nextjs:
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    image: carletonuniversity/cutheme-headless:latest
  nginx:
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nextjs
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs:/etc/nginx/certs
    environment:
      - SSL_CERT_FILE=/etc/nginx/certs/localhost.crt
      - SSL_KEY_FILE=/etc/nginx/certs/localhost.key

networks:
  its-nodedev1: