version: '3'

services:
  nextjs:
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    image: carletonuniversity/cutheme-headless:latest
    expose:
      - 3000
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs:/etc/nginx/certs
    restart: always
    environment:
      - SSL_CERT_FILE=/etc/nginx/certs/localhost.crt
      - SSL_KEY_FILE=/etc/nginx/certs/localhost.key

networks:
  its-nodedev1: